<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Chinnuboss" failures="1" tests="4" name="Test" time="61.403" errors="0" timestamp="2021-08-27T22:46:59 IST">
  <testcase classname="com.vtiger.comcast.leadtest.CreateNewLeadTest" name="creatNewLeadByInvalidAnnualRevenueTest" time="10.863">
    <skipped/>
  </testcase> <!-- creatNewLeadByInvalidAnnualRevenueTest -->
  <testcase classname="com.vtiger.comcast.leadtest.CreateNewLeadTest" name="creatNewLeadByInvalidAnnualRevenueTest" time="9.751">
    <skipped/>
  </testcase> <!-- creatNewLeadByInvalidAnnualRevenueTest -->
  <testcase classname="com.vtiger.comcast.leadtest.CreateNewLeadTest" name="creatNewLeadByInvalidAnnualRevenueTest" time="10.057">
    <skipped/>
  </testcase> <!-- creatNewLeadByInvalidAnnualRevenueTest -->
  <testcase classname="com.vtiger.comcast.leadtest.CreateNewLeadTest" name="creatNewLeadByInvalidAnnualRevenueTest" time="9.76">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.vtiger.comcast.leadtest.CreateNewLeadTest.creatNewLeadByInvalidAnnualRevenueTest(CreateNewLeadTest.java:151)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- creatNewLeadByInvalidAnnualRevenueTest -->
  <testcase classname="com.vtiger.comcast.leadtest.CreateNewLeadTest" name="creatNewLeadByValidAnnualRevenueTest" time="0.0">
    <ignored/>
  </testcase> <!-- creatNewLeadByValidAnnualRevenueTest -->
  <testcase classname="com.vtiger.comcast.leadtest.CreateNewLeadTest" name="createNewLeadByAssignToTest" time="0.0">
    <ignored/>
  </testcase> <!-- createNewLeadByAssignToTest -->
</testsuite> <!-- Test -->
